---
title: 'Ch14 hw week 14'
author: "Jin Kweon"
date: "3/16/2017"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(ggplot2, warn.conflicts = F)
library(dplyr, warn.conflicts = F)

```

#2 -a)
```{r}
table <- data.frame(c(0.34, 1.38, -0.65, 0.68, 1.40, -0.88, -0.3, -1.18, 0.5, -1.75),
                    c(0.27, 1.34, -0.53, 0.35, 1.28, -0.98, -0.72, -0.81, 0.64, -1.59))

colnames(table) <- c("x", "y")

answer <- lm(formula= table$y ~ table$x)

plot(table$x, table$y)
abline(lm(table$x ~ table$y, col = "red"))

summary(answer)


#Extra calculation just to make sure my answer is correct.
xbar <- mean(table$x)
ybar <- mean(table$y)
numerator <- (length(table$x) - 1) * cov(table$x, table$y) # multiply by 9 since it is sample, not popluation (pg 544)
denominator <- (sum((table$x - xbar)**2))

approx_b <- numerator/denominator
approx_a <- (ybar - (approx_b * xbar))
```
So, it is proved that the formulas in the book is approximately the same as the functions in R.


b)
```{r}
answer2 <- lm(formula = table$x ~ table$y)

plot(table$y, table$x)
abline(lm(table$y ~ table$x, col = "blue"))

summary(answer2)

#Extra calculation just to make sure my answer is correct.
numerator <- (length(table$y) - 1) * cov(table$y, table$x) # multiply by 9 since it is sample, not popluation (pg 544)
denominator <- (sum((table$y - ybar)**2))

approx_d <- numerator/denominator
approx_c <- (xbar - (approx_d * ybar))
```




